### ISSUE TITLE
Automated advancement of a skater's division based on birth date

### ISSUE THREAD

**Issue by jameswestover** [jameswestover/metric-issues#3]
Each year I need to manually change every skater's division at the beginning of each season (one of the reasons for 1.A above) .  By adding a birth date to the data, automatic advancement to the next level would be very useful.  This would take some design discussions so we could accommodate for Masters and any changes in the regulations in the future to avoid hard-coding the logic.

**Comment by jameswestover** [comment]
This would be a heavy feature add. Adding management of classes and the age in which a skater would align to a class would not be trivial. 

Is the real pain here managing skaters thru the UI?

**Comment by hermanja1** [comment]
Implementation of issue #4 decreases the need for this.  If the level of effort is high, let's scratch it from the list.

**Comment by jameswestover** [comment]
Ok, closed.
